### ISSUE TITLE
Google maps navigation turn arrow in notifications is missing

### ISSUE THREAD

**Issue by linyongzheng** [AmazMod/AmazMod#723]
My turn arrows have disappeared after updating my international Verge (A1811) to qogirUS-3.2.6.0, AmazMod service from 1900 to 1904 and AmazMod app to 217 (don't remember the previous app version).
 
The error in the logs is:
2019-10-22 21:46:14.469 ERROR NotificationFactory.addMapBitmap(): android.graphics.drawable.Icon cannot be cast to android.graphics.Bitmap: java.lang.ClassCastException: android.graphics.drawable.Icon cannot be cast to android.graphics.Bitmap
	at com.edotassi.amazmod.notification.factory.NotificationFactory.addMapBitmap(NotificationFactory.java:213)
	at com.edotassi.amazmod.notification.factory.NotificationFactory.fromStatusBarNotification(NotificationFactory.java:121)
	at com.edotassi.amazmod.notification.factory.NotificationFactory.getMapNotification(NotificationFactory.java:309)
	at com.edotassi.amazmod.notification.NotificationService.mapNotification(NotificationService.java:816)
	at com.edotassi.amazmod.notification.NotificationService.onNotificationPosted(NotificationService.java:251)
	at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:346)
	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2023)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2019-10-22 21:46:48.304 ERROR NotificationFactory.extractLargeIcon(): android.graphics.drawable.Icon cannot be cast to android.graphics.Bitmap: java.lang.ClassCastException: android.graphics.drawable.Icon cannot be cast to android.graphics.Bitmap
	at com.edotassi.amazmod.notification.factory.NotificationFactory.extractLargeIcon(NotificationFactory.java:151)
	at com.edotassi.amazmod.notification.factory.NotificationFactory.extractImagesFromNotification(NotificationFactory.java:139)
	at com.edotassi.amazmod.notification.factory.NotificationFactory.fromStatusBarNotification(NotificationFactory.java:118)
	at com.edotassi.amazmod.notification.NotificationService.sendNotificationWithCustomUI(NotificationService.java:377)
	at com.edotassi.amazmod.notification.NotificationService.onNotificationPosted(NotificationService.java:234)
	at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:346)
	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2023)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by fcaronte** [comment]
Umh, I do a fast check and seem working for me (I don't use as daily) do you have some special maps version or setting? Amazmod sent the maps status bar notification, so try to check on status bar if you see icon correctly

**Comment by linyongzheng** [comment]
I see the arrows in the status bar notification of my phone. I'm running on a Pixel 3, Android 10 (QP1A.191005.007), maps version 10.28.2, AmazMod Service 1904, AmazMod App version 1.1.8. Everything is from the Play store (sans the Amazmod service of course). Really don't know what is going on here.

**Comment by fcaronte** [comment]
So, probably is something related to android 10. I haven't an android 10 devices to test but I can try to ask to other user if have same problem with this android version

**Comment by fcaronte** [comment]
Oh maybe you simple forgot to add Maps on the amazmod app list to receive notifications. You need to enable the "show system app" to find it and enable

**Comment by linyongzheng** [comment]
No, I get the text directions. What I don't get is the turn arrow (left, right, straight, etc.). The logs say that it cannot cast the bitmap of the turn arrow for some reason.

The arrow is important because the text directions say things like, "50m street name" but doesn't say left turn or right turn (that is what the arrow shows), effectively rendering the directions useless.

**Comment by linyongzheng** [comment]
Just broke out an old Android 8.1 phone and paired it with my watch. Turn arrows are showing up on when I use the maps.

Seems like this is a issue with Android 10.0.

**Comment by fcaronte** [comment]
Yes I install an android 10 ROM and have same problem and noted missing contact pictures on notification too. Yes  Android 10 change something

**Comment by fcaronte** [comment]
> Just broke out an old Android 8.1 phone and paired it with my watch. Turn arrows are showing up on when I use the maps.
> 
> Seems like this is a issue with Android 10.0.

can you try last blending edge version? now maps, and contact picture should work on android 10 too! (telegram is not work and probably use another way to get contact picture because isn't work on  android Pie too)
