### ISSUE TITLE
unable to find watch on Android 10

### ISSUE THREAD

**Issue by meirlo** [AmazMod/AmazMod#802]
Hi, 
my OnePlus 6 is running the latest OxygenOS beta with Android 10.
recently Amazmod can not find my Stratos watch.
I tried to update to the bleeding edge build but it has the same issue.

here is the log

```
2020-02-05 18:48:16.523 ERROR WatchfaceReceiver.onLocationChanged(): WatchfaceDataReceiver location updated: 33.0802945,38.8554308
2020-02-05 18:48:19.372 ERROR NotificationJobService.onStartJob(): onStartJob error: null uuid!
2020-02-05 18:48:45.578 ERROR TransportService.call(): Timed out waiting for Task: java.util.concurrent.TimeoutException: Timed out waiting for Task
	at com.google.android.gms.tasks.Tasks.await(Unknown Source:32)
	at com.edotassi.amazmod.transport.TransportService$2.call(TransportService.java:349)
	at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
2020-02-05 18:49:15.600 ERROR TransportService.call(): Timed out waiting for Task: java.util.concurrent.TimeoutException: Timed out waiting for Task
	at com.google.android.gms.tasks.Tasks.await(Unknown Source:32)
	at com.edotassi.amazmod.transport.TransportService$2.call(TransportService.java:349)
	at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by meirlo** [comment]
log with debug mode enabled
```
2020-02-05 19:00:15.624 INFO  AmazModApplication.setupLogs(): Logging to /storage/emulated/0/Android/data/com.edotassi.amazmod/files/amazmod.log using the level debug
2020-02-05 19:00:15.625 DEBUG AmazModApplication.attachBaseContext(): AmazModApplication attachBaseContext
2020-02-05 19:00:15.645 INFO  AmazModApplication.onCreate(): AmazModApplication onCreate
2020-02-05 19:00:15.651 DEBUG AmazModApplication.setWatchConnected(): AmazModApplication setWatchConnected - connected: true | last seen: 2/5/20 19:00
2020-02-05 19:00:15.655 INFO  BatteryStatusReceiver.startBatteryReceiver(): BatteryStatusReceiver times: 35387557 / 0
2020-02-05 19:00:15.680 DEBUG FilesExtrasActivity.getInstalledPackagesNames(): FilesExtrasActivity getInstalledPackagesNames
2020-02-05 19:00:15.890 DEBUG MainActivity.isSystemThemeDark(): System night mode is enabled
2020-02-05 19:00:15.926 DEBUG MainActivity.onCreate(): MainActivity onCreate isWatchConnected: true
2020-02-05 19:00:15.936 INFO  BatteryStatusReceiver.startBatteryReceiver(): BatteryStatusReceiver times: 35387837 / 0
2020-02-05 19:00:15.940 DEBUG SilenceApplicationHelper.enablePackage(): SilenceApplicationHelper enablePackage: com.google.android.gm in AmazmodDB.NotificationPreferences
2020-02-05 19:00:15.942 DEBUG SilenceApplicationHelper.enablePackage(): SilenceApplicationHelper enablePackage: com.whatsapp in AmazmodDB.NotificationPreferences
2020-02-05 19:00:15.944 DEBUG SilenceApplicationHelper.enablePackage(): SilenceApplicationHelper enablePackage: org.telegram.messenger in AmazmodDB.NotificationPreferences
2020-02-05 19:00:15.945 INFO  FilesExtrasActivity.loadAppsPrefsFromJSON(): FilesExtrasActivity loadAppsPrefsFromJSON finished
2020-02-05 19:00:15.946 DEBUG FilesExtrasActivity.loadAppsPrefsFromJSON(): FilesExtrasActivity loadAppsPrefsFromJSON filters: []
2020-02-05 19:00:15.947 DEBUG FilesExtrasActivity.getInstalledPackagesNames(): FilesExtrasActivity getInstalledPackagesNames
2020-02-05 19:00:16.069 DEBUG MainActivity.onResume(): MainActivity onResume isWatchConnected: true
2020-02-05 19:00:16.070 DEBUG BatteryChartFragment.onResume(): BatteryChartFragment onResume
2020-02-05 19:00:16.072 DEBUG SilencedApplicationsFragment.onResume(): SilencedApplicationsFragment onResume
2020-02-05 19:00:16.235 DEBUG NotificationService.onCreate(): onCreate
2020-02-05 19:00:16.238 DEBUG TransportService.onCreate(): TransportService onCreate
2020-02-05 19:00:16.243 DEBUG TransportService.tryReconnectNotificationService(): TransportService tryReconnectNotificationService
2020-02-05 19:00:16.244 INFO  TransportService.toggleNotificationService(): TransportService toggleNotificationService
2020-02-05 19:00:16.245 DEBUG TransportService.tryReconnectNotificationService(): TransportService tryReconnectNotificationService requestRebind
2020-02-05 19:00:16.248 WARN  TransportService.connectTransporterAmazMod(): TransportService onCreate transporterAmazMod not connected, connecting...
2020-02-05 19:00:16.250 DEBUG AmazModApplication.setWatchConnected(): AmazModApplication setWatchConnected - connected: false | last seen: 2/5/20 19:00
2020-02-05 19:00:16.251 WARN  TransportService.connectTransporterNotifications(): TransportService transporterNotifications not connected, connecting...
2020-02-05 19:00:16.251 WARN  TransportService.connectTransporterHuami(): onStartJob transporterHuami not connected, connecting...
2020-02-05 19:00:16.252 WARN  TransportService.connectTransporterCompanion(): onStartJob transporterCompanion not connected, connecting...
2020-02-05 19:00:16.253 DEBUG TransportService.onStartCommand(): TransportService onStartCommand
2020-02-05 19:00:16.257 DEBUG TransportService.onStartCommand(): TransportService onStartCommand
2020-02-05 19:00:16.269 DEBUG MainActivity.isSystemThemeDark(): System night mode is enabled
2020-02-05 19:00:16.294 DEBUG MainActivity.onCreate(): MainActivity onCreate isWatchConnected: false
2020-02-05 19:00:16.297 INFO  BatteryStatusReceiver.startBatteryReceiver(): BatteryStatusReceiver times: 35388199 / 0
2020-02-05 19:00:16.303 DEBUG FilesExtrasActivity.getInstalledPackagesNames(): FilesExtrasActivity getInstalledPackagesNames
2020-02-05 19:00:16.402 DEBUG MainActivity.onResume(): MainActivity onResume isWatchConnected: false
2020-02-05 19:00:16.403 DEBUG BatteryChartFragment.onResume(): BatteryChartFragment onResume
2020-02-05 19:00:16.405 DEBUG SilencedApplicationsFragment.onResume(): SilencedApplicationsFragment onResume
2020-02-05 19:00:16.533 DEBUG TransportService.onStartCommand(): TransportService onStartCommand
2020-02-05 19:00:16.560 DEBUG NotificationService.onListenerConnected(): onListenerConnected
2020-02-05 19:00:16.566 DEBUG NotificationService.cancelPendingJobs(): cancelPendingJobs pendingJobs: 7
2020-02-05 19:00:16.566 DEBUG NotificationService.cancelPendingJobs(): cancelPendingJobs jobInfo: (job:3776/com.edotassi.amazmod/.notification.NotificationJobService)
2020-02-05 19:00:16.567 DEBUG NotificationService.cancelPendingJobs(): cancelPendingJobs jobInfo: (job:7560/com.edotassi.amazmod/.notification.NotificationJobService)
2020-02-05 19:00:16.567 DEBUG NotificationService.cancelPendingJobs(): cancelPendingJobs jobInfo: (job:1114/com.edotassi.amazmod/.notification.NotificationJobService)
2020-02-05 19:00:16.567 DEBUG NotificationService.cancelPendingJobs(): cancelPendingJobs jobInfo: (job:7398/com.edotassi.amazmod/.notification.NotificationJobService)
2020-02-05 19:00:16.568 DEBUG NotificationService.cancelPendingJobs(): cancelPendingJobs jobInfo: (job:1068/com.edotassi.amazmod/.notification.NotificationJobService)
2020-02-05 19:00:16.568 DEBUG NotificationService.cancelPendingJobs(): cancelPendingJobs jobInfo: (job:1055/com.edotassi.amazmod/.notification.NotificationJobService)
2020-02-05 19:00:16.568 DEBUG NotificationService.cancelPendingJobs(): cancelPendingJobs jobInfo: (job:0/com.edotassi.amazmod/.notification.NotificationJobService)
2020-02-05 19:00:16.570 DEBUG NotificationService.scheduleJob(): id: 0 jobId: 0 uuid: null
2020-02-05 19:00:16.578 DEBUG TransportService.onStartCommand(): TransportService onStartCommand
2020-02-05 19:00:16.583 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted notificationPosted: 0|com.edotassi.amazmod|999989|null|10402
2020-02-05 19:00:16.585 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted blocked: com.edotassi.amazmod / P
2020-02-05 19:00:16.600 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted notificationPosted: 0|com.edotassi.amazmod|999989|null|10402
2020-02-05 19:00:16.601 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted blocked: com.edotassi.amazmod / P
2020-02-05 19:00:16.602 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted notificationPosted: 0|com.edotassi.amazmod|999989|null|10402
2020-02-05 19:00:16.603 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted blocked: com.edotassi.amazmod / P
2020-02-05 19:00:16.603 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted notificationPosted: 0|com.edotassi.amazmod|999989|null|10402
2020-02-05 19:00:16.604 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted blocked: com.edotassi.amazmod / P
2020-02-05 19:00:16.604 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted notificationPosted: 0|com.edotassi.amazmod|999989|null|10402
2020-02-05 19:00:16.605 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted blocked: com.edotassi.amazmod / P
2020-02-05 19:00:16.606 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted notificationPosted: 0|com.edotassi.amazmod|999989|null|10402
2020-02-05 19:00:16.607 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted blocked: com.edotassi.amazmod / P
2020-02-05 19:00:16.635 DEBUG TransportService.send(): TransportService sendUsingTransporter action: request_watchstatus
2020-02-05 19:00:16.635 DEBUG NotificationJobService.keepNotificationServiceRunning(): keepNotificationServiceRunning
2020-02-05 19:00:16.636 DEBUG AmazModApplication.setWatchConnected(): AmazModApplication setWatchConnected - connected: false | last seen: 2/5/20 19:00
2020-02-05 19:00:16.636 DEBUG NotificationJobService.keepNotificationServiceRunning(): keepNotificationServiceRunning requestRebind
2020-02-05 19:00:16.636 DEBUG PersistentNotification.updatePersistentNotification(): PersistentNotification updatePersistentNotification isConnected: false
2020-02-05 19:00:16.637 DEBUG NotificationJobService.onStartJob(): onStartJob id: 0 \ mode: -1 \ uuid: null
2020-02-05 19:00:16.637 DEBUG NotificationJobService.onStartJob(): onStartJob std#: 0 \ cst#: 0 \ rmv#: 0
2020-02-05 19:00:16.637 ERROR NotificationJobService.onStartJob(): onStartJob error: null uuid!
2020-02-05 19:00:16.641 DEBUG MainActivity.getTransportStatus(): MainActivity getTransportStatus: false
2020-02-05 19:00:16.642 DEBUG MainActivity.getTransportStatus(): MainActivity getTransportStatus: false
2020-02-05 19:00:16.642 WARN  TransportService.send(): transpoterAmazMod not connected
2020-02-05 19:00:16.653 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted notificationPosted: 0|com.edotassi.amazmod|999989|null|10402
2020-02-05 19:00:16.655 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted blocked: com.edotassi.amazmod / P
2020-02-05 19:00:16.656 DEBUG NotificationJobService.onDestroy(): onDestroy
2020-02-05 19:00:16.657 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted notificationPosted: 0|com.edotassi.amazmod|999989|null|10402
2020-02-05 19:00:16.658 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted blocked: com.edotassi.amazmod / P
2020-02-05 19:00:16.684 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted notificationPosted: 0|com.edotassi.amazmod|999989|null|10402
2020-02-05 19:00:16.687 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted blocked: com.edotassi.amazmod / P
2020-02-05 19:00:16.688 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted notificationPosted: 0|com.edotassi.amazmod|999989|null|10402
2020-02-05 19:00:16.689 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted blocked: com.edotassi.amazmod / P
2020-02-05 19:00:16.700 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted notificationPosted: 0|com.edotassi.amazmod|999989|null|10402
2020-02-05 19:00:16.702 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted blocked: com.edotassi.amazmod / P
2020-02-05 19:00:16.702 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted notificationPosted: 0|com.edotassi.amazmod|999989|null|10402
2020-02-05 19:00:16.704 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted blocked: com.edotassi.amazmod / P
2020-02-05 19:00:16.766 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted notificationPosted: 0|com.edotassi.amazmod|999989|null|10402
2020-02-05 19:00:16.768 DEBUG NotificationService.onNotificationPosted(): onNotificationPosted blocked: com.edotassi.amazmod / P
2020-02-05 19:00:21.161 DEBUG StatsActivity.onCreate(): logFile: /storage/emulated/0/Android/data/com.edotassi.amazmod/files/amazmod.log

```

**Comment by fcaronte** [comment]
I use as daily edgy version on miui with Android 10 and work normally, try to check permission and to have the right edgy version Because the is one version stop to update correctly

**Comment by meirlo** [comment]
Can you specify which permission is missing?
As I think I've granted all permission, and also disable the battery optimization.
I think the version on OnePlus is newer than the MIUI 
Google system version is 292003300 And the security patch is from December 1, 2019.

**Comment by fcaronte** [comment]
Have you check notification access or reinstall again phone and watch. I
will try to see log when I go to pc

Il mer 5 feb 2020, 20:09 meirlo <notifications@github.com> ha scritto:

**Comment by meirlo** [comment]
yes, I uninstall and install the app and the service before installing the edgy version.
the app has notification access.

**Comment by fcaronte** [comment]
> yes, I uninstall and install the app and the service before installing the edgy version.
> but I'll try to do that again and update if there is any change.
> the app has notification access.

is possible you forgot to remove device admin before uninstall service? if yes you haven't really remove it and so you have the 1904 version. check if service version is 1905.
is the amazfit app connected correctly?

**Comment by meirlo** [comment]
version is indeed 1905.
The Amazfit app is connected correctly.
also, I'm using Amazfit Battery Tile and it shows the correct battery level.

**Comment by GreatApo** [comment]
I think Amazfit Battery Tile makes a request through Amazfit app. Indeed your log shows that Amazmod can't find the watch, I don't know why though.

**Comment by meirlo** [comment]
I'm starting to suspect Amazfit Battery Tile is somehow blocking the connection.
I removed it and Amazmod seems to work for now.
I'll check that during the following week and report back.

Thanks,
Meir

**Comment by meirlo** [comment]
unfortunately, Amazfit Battery Tile is not the issue.
after turning off both watch and phone, Amazmod is failed to find the phone again.
Attached log file.
[amazmod (3).log](https://github.com/AmazMod/AmazMod/files/4175254/amazmod.3.log)

**Comment by 1immortal** [comment]
@meirlo - can you please check with latest edgy/release and report back?

**Comment by meirlo** [comment]
updated to the latest edgy 1.1.9-dev (Build 220)
still having the same issue:
> 2020-04-04 09:16:59.433 ERROR NotificationJobService.onStartJob(): onStartJob error: null uuid!

**Comment by fcaronte** [comment]
Can you give an watch side log? @meirlo

**Comment by meirlo** [comment]
So I'm not sure how, but it works fine again and seems to be stable.
I'm closing the issue for now.
will re-open it with logs if it will happen again.
Thanks,
Meir
